module.exports = {
  NOT_FOUND_MSG: "NOT_FOUND_ERROR",
  INPUTS_ERROR_MSG: "INPUTS_ERROR",
  UNAUTHORIZED_AUTH_ERROR_MSG: "UNAUTHORIZED_AUTH_ERROR",
  CAPTCHA_ERROR_MSG: "CAPTCHA_ERROR",
  MONGOOSE_ERROR_MSG: "MONGOOSE_ERROR",
  UNEXPECTED_ERROR_MSG: "UNEXPECTED_ERROR",
  PARENT_NOT_FOUND_ERROR_MSG: "PARENT_NOT_FOUND_ERROR",
  PARENT_HAS_FULL_CHILDREN_ERROR_MSG: "PARENT_HAS_FULL_CHILDREN_ERROR",
  EMAIL_ALREADY_EXISTS_ERROR_MSG: "EMAIL_ALREADY_EXISTS_ERROR",
  CLIENT_DOES_NOT_EXISTS_ERROR_MSG: "CLIENT_DOES_NOT_EXISTS_ERROR",
  CLIENT_PASSWORD_AND_EMAIL_DOES_NOT_MATCH_ERROR_MSG:
    "CLIENT_PASSWORD_AND_EMAIL_DOES_NOT_MATCH_ERROR",
  CLIENT_SEND_RESET_PASSWORD_EMAIL_ERROR_MSG:
    "CLIENT_SEND_RESET_PASSWORD_EMAIL_ERROR",
  CLIENT_PASSWORD_RESET_DOES_NOT_EXISTS_ERROR_MSG:
    "CLIENT_PASSWORD_RESET_DOES_NOT_EXISTS_ERROR",
  CLIENT_PASSWORD_RESET_EXPIRED_ERROR_MSG:
    "CLIENT_PASSWORD_RESET_EXPIRED_ERROR",
  GET_CLIENT_TREE_NOT_ALLOWED_ERROR_MSG: "GET_CLIENT_TREE_NOT_ALLOWED_ERROR",
  CLIENT_UPDATE_NOT_ALLOWED_ERROR_MSG: "CLIENT_UPDATE_NOT_ALLOWED_ERROR",
  // rate limits errors
  TOO_MANY_REQUESTS_ERROR_MSG: "TOO_MANY_REQUESTS_ERROR",
  CONTACT_TOO_MANY_REQUESTS_ERROR_MSG: "CONTACT_TOO_MANY_REQUESTS_ERROR",
  CLIENT_TOO_MANY_REQUESTS_ERROR_MSG: "CLIENT_TOO_MANY_REQUESTS_ERROR",
};
