const AMOUNT_TO_PAY_BY_CHILD = 7.5; // 7.5 TND
const FIXED_AMOUNT_AFTER_10_HEIGHT = 1000; // 1 MILLION
const TOTAL_AMOUNT_BEFORE_10_HEIGHT = 2046 * AMOUNT_TO_PAY_BY_CHILD; // 15345 TND

module.exports = {
  AMOUNT_TO_PAY_BY_CHILD,
  FIXED_AMOUNT_AFTER_10_HEIGHT,
  TOTAL_AMOUNT_BEFORE_10_HEIGHT,
};
