module.exports = {
  NOT_FOUND_MSG: "NOT_FOUND_ERROR",
  CAPTCHA_ERROR_MSG: "CAPTCHA_ERROR",
  MONGOOSE_ERROR_MSG: "MONGOOSE_ERROR",
  UNEXPECTED_ERROR_MSG: "UNEXPECTED_ERROR",
  PARENT_NOT_FOUND_ERROR_MSG: "PARENT_NOT_FOUND_ERROR",
  PARENT_HAS_FULL_CHILDREN_ERROR_MSG: "PARENT_HAS_FULL_CHILDREN_ERROR",
  EMAIL_ALREADY_EXISTS_ERROR_MSG: "EMAIL_ALREADY_EXISTS_ERROR",
};
